name: Deploy to GitHub Pages

on:
  push:
    branches: ['page']

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: pages
  cancel-in-progress: true

jobs:
  build-and-deploy:
    environment:
      name: github-pages
      url: ${{ steps.deploy.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup PNPM
        uses: pnpm/action-setup@v4
        with:
          version: 10
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
      - name: setup pages
        uses: actions/configure-pages@v5
      - name: install deps
        run: pnpm install
      - name: build
        run: pnpm build
      - name: upload
        uses: actions/upload-pages-artifact@v4
        with:
          path: dist
      - name: deploy
        id: deploy
        uses: actions/deploy-pages@v4
